name: Release Richer to PyPI

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install jaclang from source
        run: |
          git clone https://github.com/jaseci-labs/jaseci.git
          cd jaseci/jac
          pip install .

      - name: Install twine
        run: pip install twine

      - name: Build and publish package
        run: |
          jac bundle
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
